apiVersion: v1
kind: PersistentVolume
metadata:
  name: "netdata-0"
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/netdata"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "netdata-1"
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/netdata"
