parent:
  port: 19999
  resources: {}

  livenessProbe:
    failureThreshold: 3
    periodSeconds: 30
    successThreshold: 1
    timeoutSeconds: 1
  readinessProbe:
    failureThreshold: 3
    periodSeconds: 30
    successThreshold: 1
    timeoutSeconds: 1

  terminationGracePeriodSeconds: 10

  nodeSelector: {}

  tolerations: []

  affinity: {}

  priorityClassName: ""

  env:
    DO_NOT_TRACK: 1

  podLabels: {}

  podAnnotations: {}

  database:
    persistence: true
    volumesize: 2Gi

  alarms:
    persistence: true
    volumesize: 1Gi

  configs:  # parent's config
    netdata:
      enabled: true
      path: /etc/netdata/netdata.conf
      data: |
        [global]
          memory mode = save
        [plugins]
          cgroups = no
          tc = no
          enable running new plugins = no
          check for new plugins every = 72000
          python.d = no
          charts.d = no
          go.d = no
          node.d = no
          apps = no
          proc = no
          idlejitter = no
          diskspace = no
    health:
      enabled: true
      path: /etc/netdata/health_alarm_notify.conf
      data: |
        SEND_EMAIL="YES"
        role_recipients_email[sysadmin]=dongho971220@gmail.com
    stream:
      enabled: true
      path: /etc/netdata/stream.conf
      data: |
        [3064c61b-27c3-4df4-bfd7-daaecea58804]
          enabled = yes
          history = 3600
          default memory mode = save
          health enabled by default = auto
          allow from = *

child:
  enabled: true
  updateStrategy: {}

  resources: {}

  livenessProbe:
    failureThreshold: 3
    periodSeconds: 30
    successThreshold: 1
    timeoutSeconds: 1
  readinessProbe:
    failureThreshold: 3
    periodSeconds: 30
    successThreshold: 1
    timeoutSeconds: 1

  terminationGracePeriodSeconds: 10

  nodeSelector: {}

  tolerations:
    - operator: Exists
      effect: NoSchedule

  affinity: {}

  priorityClassName: ""

  podLabels: {}

  podAnnotationAppArmor:
    enabled: true

  podAnnotations: {}

  persistence:
    enabled: true
    hostPath: /var/lib/netdata-k8s-child

  configs:  # child's config
    netdata:
      enabled: true
      path: /etc/netdata/netdata.conf
      data: |
        [global]
          memory mode = none
        [health]
          enabled = no
        [plugins]
          PATH environment variable = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin
          PYTHONPATH environment variable =
          proc = yes
          diskspace = yes
          timex = no
          cgroups = no
          tc = no
          idlejitter = no
          enable running new plugins = no
          check for new plugins every = 60
          slabinfo = no
          node.d = no
          perf = no
          fping = no
          go.d = no
          ioping = no
          python.d = yes
          apps = no
          charts.d = no
          freeipmi = no
        [plugin:proc]
          netdata server resources = yes
          /proc/pagetypeinfo = no
          /proc/stat = yes
          /proc/uptime = yes
          /proc/loadavg = yes
          /proc/sys/kernel/random/entropy_avail = yes
          /proc/pressure = yes
          /proc/interrupts = yes
          /proc/softirqs = yes
          /proc/vmstat = yes
          /proc/meminfo = yes
          /sys/kernel/mm/ksm = no
          /sys/block/zram = no
          /sys/devices/system/edac/mc = no
          /sys/devices/system/node = no
          /proc/net/dev = yes
          /proc/net/wireless = no
          /proc/net/sockstat = yes
          /proc/net/sockstat6 = no
          /proc/net/netstat = no
          /proc/net/snmp = yes
          /proc/net/snmp6 = no
          /proc/net/sctp/snmp = no
          /proc/net/softnet_stat = no
          /proc/net/ip_vs/stats = no
          /sys/class/infiniband = no
          /proc/net/stat/conntrack = no
          /proc/net/stat/synproxy = no
          /proc/diskstats = yes
          /proc/mdstat = no
          /proc/net/rpc/nfsd = no
          /proc/net/rpc/nfs = no
          /proc/spl/kstat/zfs/arcstats = no
          /proc/spl/kstat/zfs/pool/state = no
          /sys/fs/btrfs = no
          ipc = no
          /sys/class/power_supply = no
    stream:
      enabled: true
      path: /etc/netdata/stream.conf
      data: |
        [stream]
          enabled = yes
          destination = netdata:{{ .Values.service.port }}
          api key = 3064c61b-27c3-4df4-bfd7-daaecea58804
          timeout seconds = 60
          buffer size bytes = 1048576
          reconnect delay seconds = 5
          initial clock resync iterations = 60
    kubelet:
      enabled: true
      path: /etc/netdata/go.d/k8s_kubelet.conf
      data: |
        update_every: 1
        autodetection_retry: 0
        jobs:
          - url: http://127.0.0.1:10255/metrics
          - url: https://localhost:10250/metrics
            tls_skip_verify: yes
    kubeproxy:
      enabled: true
      path: /etc/netdata/go.d/k8s_kubeproxy.conf
      data: |
        update_every: 1
        autodetection_retry: 0
        jobs:
          - url: http://127.0.0.1:10249/metrics
  env:
    DO_NOT_TRACK: 1

replicaCount: 1
deploymentStrategy:
  type: Recreate

image:
  repository: localhost:5000/santabpf
  tag: v1.31.0
  pullPolicy: Always

sd:
  repository: netdata/agent-sd
  tag: v0.2.1
  pullPolicy: Always
  child:
    enabled: true
    configmap:
      name: netdata-child-sd-config-map
      key: config.yml
      from:
        file: sdconfig/child.yml
        value: {}
    resources:
      limits:
        cpu: 50m
        memory: 150Mi
      requests:
        cpu: 50m
        memory: 100Mi

sysctlImage:
  enabled: true
  repository: alpine
  tag: latest
  pullPolicy: Always
  command: []
  resources: {}

wgetImage:
  repository: netdata/wget
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  nodePort: 29999
  annotations: {}

ingress:
  enabled: false

rbac:
  create: true
  pspEnabled: true

serviceAccount:
  create: true
  name: netdata
