apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "netdata.name" . }}-parent
  labels:
    app: {{ template "netdata.name" . }}
    chart: {{ template "netdata.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: parent
  annotations:
    timestamp: "{{ .Values.timestamp }}"
spec:
  replicas: {{ .Values.replicaCount }}
  strategy: {{- toYaml .Values.deploymentStrategy | nindent 4 }}
  selector:
    matchLabels:
      app: {{ template "netdata.name" . }}
      release: {{ .Release.Name }}
      role: parent
  template:
    metadata:
      labels:
        app: {{ template "netdata.name" . }}
        release: {{ .Release.Name }}
        role: parent
{{- with .Values.parent.podLabels }}
{{ toYaml . | trim | indent 8 }}
{{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
{{- with .Values.parent.podAnnotations }}
{{ toYaml . | trim | indent 8 }}
{{- end }}
    spec:
      hostname: master
      hostPID: true
      securityContext:
        fsGroup: 201
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- if .Values.parent.priorityClassName }}
      priorityClassName: "{{ .Values.parent.priorityClassName }}"
      {{- end }}
      initContainers:
      {{- if .Values.sysctlImage.enabled }}
        - name: init-sysctl
          image: "{{ .Values.sysctlImage.repository }}:{{ .Values.sysctlImage.tag }}"
          imagePullPolicy: {{ .Values.sysctlImage.pullPolicy }}
          command:
{{ toYaml .Values.sysctlImage.command | indent 12 }}
          securityContext:
            runAsNonRoot: false
            privileged: true
            runAsUser: 0
          resources:
{{ toYaml .Values.sysctlImage.resources | indent 12 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ tpl .Values.image.tag . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          - configMapRef:
              name: netdata-auth
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NETDATA_LISTENER_PORT
              value: '{{ .Values.parent.port }}'
            {{- range $key, $value := .Values.parent.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.parent.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v1/info
              port: http
            failureThreshold: {{ .Values.parent.livenessProbe.failureThreshold }}
            periodSeconds: {{ .Values.parent.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.parent.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.parent.livenessProbe.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: /api/v1/info
              port: http
            failureThreshold: {{ .Values.parent.readinessProbe.failureThreshold }}
            periodSeconds: {{ .Values.parent.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.parent.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.parent.readinessProbe.timeoutSeconds }}
          volumeMounts:
            {{- range $name, $config := .Values.parent.configs }}
            {{- if $config.enabled }}
            - name: config
              mountPath: {{ $config.path }}
              subPath: {{ $name }}
            {{- end }}
            {{- end }}
            {{- if .Values.parent.database.persistence }}
            - name: database
              mountPath: /var/cache/netdata
            {{- end }}
            {{- if .Values.parent.alarms.persistence }}
            - name: alarms
              mountPath: /var/lib/netdata
            {{- end }}
            - name: proc
              readOnly: true
              mountPath: /host/proc
            - name: run
              mountPath: /var/run/docker.sock
            - name: sys
              readOnly: true
              mountPath: /host/sys
            - name: src
              readOnly: true
              mountPath: /usr/src
            - name: modules
              readOnly: true
              mountPath: /lib/modules
            - name: debug
              readOnly: true
              mountPath: /sys/kernel/debug
            - name: passwd
              readOnly: true
              mountPath: /host/etc/passwd
            - name: group
              readOnly: true
              mountPath: /host/etc/group
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
            capabilities:
              add:
                - SYS_PTRACE
                - SYS_ADMIN
                - CAP_SYS_ADMIN
                - CAP_SYSLOG
          resources:
{{ toYaml .Values.parent.resources | indent 12 }}
    {{- with .Values.parent.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.parent.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.parent.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      terminationGracePeriodSeconds: {{ .Values.parent.terminationGracePeriodSeconds }}
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: run
          hostPath:
            path: /var/run/docker.sock
        - name: sys
          hostPath:
            path: /sys
        - name: src
          hostPath:
            path: /usr/src
        - name: modules
          hostPath:
            path: /lib/modules
        - name: debug
          hostPath:
            path: /sys/kernel/debug
        - name: passwd
          hostPath:
            path: /etc/passwd
        - name: group
          hostPath:
            path: /etc/group
        - name: config
          configMap:
            name: netdata-conf-parent
        {{- if .Values.parent.database.persistence }}
        - name: database
          persistentVolumeClaim:
            claimName: {{ template "netdata.name" . }}-parent-database
        {{- end }}
        {{- if .Values.parent.alarms.persistence }}
        - name: alarms
          persistentVolumeClaim:
            claimName: {{ template "netdata.name" . }}-parent-alarms
        {{- end }}
